baseURL = "https://bodysys.netlify.app/"
languageCode = "en-us"
title = "Bodysys21"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Home"
url     = "/"
weight  = 1
[[menu.main]]
name    = "Organisers"
url     = "about"
weight  = 2
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 3
[[menu.main]]
name    = "Wearsys-2020"
url     = "https://sites.google.com/view/wearsys"
weight  = 3

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
#description = "Airspace Hugo theme"
#author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "Bodysys 2021"
description = "Workshop on Body-Centric Computing Systems (Previously Wearsys)"
description2 = "ACM Bodysys 2021 Workshops"
# button
btn     = true
btnText = "Submit Papers"
btnURL  = "https://bodysys2021.hotcrp.com/"

# flip text
[[params.banner.flipText]]
title   = "Human-in the loop systems"
[[params.banner.flipText]]
title   = "Physical rehabilitation systems"
[[params.banner.flipText]]
title   = "Sensing and Computing for Animals or Pets"
[[params.banner.flipText]]
title   = "XR wearables, wearable imaging"
[[params.banner.flipText]]
title   = "XR projection and low-power displays"
[[params.banner.flipText]]
title   = "Capacitive sensing"
[[params.banner.flipText]]
title   = "Capacitive sensing"
[[params.banner.flipText]]
title   = "On-body communication"
[[params.banner.flipText]]
title   = "Haptics and cognitive prosthetics"
[[params.banner.flipText]]
title   = "Body energy harnessing"
[[params.banner.flipText]]
title   = "Brain-interfaces"
[[params.banner.flipText]]
title   = "Electromyography (EMG) interfaces"


# Homepage About Section
[params.about]
enable  = true
title   = "BODYSYS"
content = "BodySys workshop focuses on advances and discussions on how body-centric (human/animals) computing technologies can shape mobile computing, systems, and applications research. The goal of the workshop is to provide a forum to bring together researchers and de-sign experts to discuss how wearable, body-centric, and user-in-the-loop technologies have, and can, complement mobile systems research, and vice-versa. It also aims to provide a launchpad for bold and visionary ideas for systems research in this space.<br> <br> We solicit papers of six or fewer pages that present preliminary research in areas of body-centric computing, including efforts on prototyping a system, experiences in designing a novel technology, or survey of useful tools for designing inter-disciplinary systems and applications. We also encourage position papers that propose new directions for research or advocate disruptive design ideas and project applications. We also encourage sub-missions that can help bootstrap exploration of the body-centric computing space by the broader mobile systems community. <h4>Important Dates:</h4><br> <dl> <dt>Submission deadline</dt> <dd>- May 21, 2021 (Midnight US-EST) <dt>Notification of acceptance:</dt> <dd>- June 4, 2021</dd> <dt>Camera-ready workshop papers</dt> <dd>- June 18, 2021</dd> <dt>Workshop date</dt> <dd>- June 24, 2021 or June 25, 2021 (to be finalised soon)</dd> </dl>"
image   = "images/wearable_banner.jpeg"

# Call to Action
[params.cta]
enable  = true
title   = "Call for Papers & SUBMISSION INSTRUCTIONS"
content = "<b>Submissions can be of the following formats:</b><br>We solicit papers of 6 or fewer pages that present preliminary research in areas of body-centric computing, including efforts on prototyping a system, experiences in designing a novel technology, or survey of useful tools for designing inter-disciplinary systems and applications. <br>We solicit <b>position papers of 1-2 pages that propose new directions </b>for research or advocate disruptive design ideas and project applications. We also encourage submissions that can help bootstrap exploration of the body-centric computing space by the broader mobile systems community. These submissions can also be submitted as a <b>poster or demo paper (1-2 pages).</b><br>All submissions should comply with  <a href=https://www.sigmobile.org/mobisys/2021/wsl.html> MobiSys guidelines  </a>. The reviewing process will be double–blind."
content2 = "<p style=\"text-align:left;font-size:120%\"> The focus areas include, but not limited to, </p> <table style=\"text-align:left;face=\"verdana\"> <tr> <td >• Human-in the loop systems </td> <td >• Physical rehabilitation systems </tr> <tr> <td >• Sensing and Computing for Animals or Pets <td >• XR wearables, wearable imaging, projection and low-power displays </tr> <tr> <td >• Capacitive sensing and On-body communication <td >• Wearable health and wellness including activity monitoring, physiological sensing </tr> <tr> <td >• Ubiquitous Input Devices <td >• Novel energy management solutions (eg. swappable batteries, solar harvesting) </tr> <tr> <td >• Context sensitive notification delivery <td >Wearable biometrics for payment and authentication </tr> <tr> <td >• Haptics and cognitive prosthetics <td >• Body energy harnessing </tr> <tr> <td >• Brain-interfaces <td >• Electromyography (EMG) interfacesWearable fashion (eg. smart jackets, bodysuits, amulets), smart fabrics </tr> <tr> <td >• AI on wearables: on-device ML/DL for wearable computing <td >• Novel combinations of 3D printing and Wear- ables (eg. integration with custom 3D printed sen- sors/encl.)<li>Wearable infrastructure and toolkits (hardware/software, custom/open source) </tr> </table>"
btnText = "HotCRP portal"
btnURL  = "https://bodysys2021.hotcrp.com/"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "The focus areas include, but not limited to,"
subtitle= "Human-in the loop systems • Physical rehabilitation systems • Sensing and Computing for Animals or Pets • XR wearables, wearable imaging, projection and low-power displays • Capacitive sensing and On-body communication • Wearable health and wellness including activity monitoring, physiological sensing • Ubiquitous Input Devices • Novel energy management solutions (eg. swappable batteries, solar harvesting) • Context sensitive notification delivery • Wearable biometrics for payment and authentication • Haptics and cognitive prosthetics • Body energy harnessing • Brain-interfaces • Electromyography (EMG) interfacesWearable fashion (eg. smart jackets, bodysuits, amulets), smart fabrics • AI on wearables: on-device ML/DL for wearable computing • Novel combinations of 3D printing and Wear- ables (eg. integration with custom 3D printed sen- sors/encl.) • Wearable infrastructure and toolkits (hardware/software, custom/open source)"

[params.team]
enable = true
# social icon
#[[params.socialIcon]]
#icon = "ion-social-facebook"
#url = "#"

#[[params.socialIcon]]
#icon = "ion-social-instagram"
#url = "#"

#[[params.socialIcon]]
#icon = "ion-social-linkedin"
#url = "#"

#[[params.gallery]]